// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1574102544);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1574102664);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1574102184);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1574102304);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1574102424);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1573755292);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1574102784);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 30885);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1573754542);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e824c23c-5500-43ec-a773-95ae590f1899}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1574103515944");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1574105288944");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1574101725077");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1574105325077");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191022215001");
user_pref("browser.slowStartup.averageTime", 6472);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20191022215001");
user_pref("browser.startup.homepage_override.mstone", "68.2.0");
user_pref("browser.startup.lastColdStartupCheck", 1574109691);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1573754545691");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "68.2.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 15 Nov 2019 07:50:24 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1574102545);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191022215001");
user_pref("extensions.lastAppVersion", "68.2.0");
user_pref("extensions.lastPlatformVersion", "68.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"2d4ed2b2-42fe-4a08-aca2-c57ebfc794f6\",\"fxmonitor@mozilla.org\":\"1e35e74b-dc6b-4826-8c1e-9cbaff23ae51\",\"screenshots@mozilla.org\":\"620526ae-ec63-4ca6-9716-07a2cd131419\",\"webcompat-reporter@mozilla.org\":\"805fdab9-62e6-4e46-bfc1-840c22ace105\",\"webcompat@mozilla.org\":\"fbb2152e-e0f4-4515-b48c-89255a3f3e7c\",\"default-theme@mozilla.org\":\"ef4adc2c-e23d-4a99-ab56-51659a947230\",\"google@search.mozilla.org\":\"b417c942-bafc-4299-ab16-f4476b68ba09\",\"bing@search.mozilla.org\":\"13b18c01-f1d7-4f13-a5ed-0fd9866ca06c\",\"ddg@search.mozilla.org\":\"d64c0035-835f-460f-93e6-ac32199cbed2\",\"mercadolivre@search.mozilla.org\":\"85a19b38-4f67-4873-9767-d99825bec14a\",\"twitter@search.mozilla.org\":\"9b8d5511-2179-4ee9-a094-225910b508d4\",\"wikipedia@search.mozilla.org\":\"c0cfcadb-21c0-4f1f-9461-204dee31a790\"}");
user_pref("idle.lastDailyNotification", 1574102765);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1574102546);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191022215001");
user_pref("media.gmp-manager.lastCheck", 1574102632);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1573754750);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "fe22327b-bd37-41df-9a56-8b601a6853f9");
user_pref("security.sandbox.plugin.tempDirSuffix", "50b2f7fe-a5d8-42cc-8226-4b68cb86f760");
user_pref("services.blocklist.pinning.checked", 1574102593);
user_pref("services.settings.clock_skew_seconds", -169);
user_pref("services.settings.last_etag", "\"1574097948904\"");
user_pref("services.settings.last_update_seconds", 1574102593);
user_pref("services.settings.main.cfr-fxa.last_check", 1574102593);
user_pref("services.settings.main.cfr.last_check", 1574102593);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1574102593);
user_pref("services.settings.main.hijack-blocklists.last_check", 1574102593);
user_pref("services.settings.main.language-dictionaries.last_check", 1574102593);
user_pref("services.settings.main.sites-classification.last_check", 1574102593);
user_pref("services.settings.main.tippytop.last_check", 1574102593);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1574102593);
user_pref("services.settings.security.onecrl.checked", 1574102593);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1573754750);
user_pref("toolkit.startup.last_success", 1574109685);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20191022215001");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
